### ISSUE TITLE
Add a button in tool bar

### ISSUE THREAD

**Issue by mOrfiUs** [kyo-ago/enable-right-click#1]
Works fine!. In Webs with useful right click (like mega) just escape or disable temporaly.(four stars)
improve: a button in tool bar for fast enable/disable temporaly

**Comment by kyo-ago** [comment]
Thank you for your comment.
ok, I understand.
Implementation to the next.

**Comment by kyo-ago** [comment]
Done.

**Comment by mOrfiUs** [comment]
Thanks!! I'll try it now

**Comment by kyo-ago** [comment]
The screenshot has been added.
