### ISSUE TITLE
Exception when opening a web site that uses the postMessage API

### ISSUE THREAD

**Issue by steph643** [kyo-ago/enable-right-click#2]
I got this error in the console when opening a web site that uses the `postMessage` javascript API to send messages from an iFrame to the parent page:
```
Uncaught TypeError: Cannot read property 'type' of undefined
    at chrome-extension://hhojmcideegachlhfgfdhailpfhgknjm/web_accessible_resources/index.js:87
```

**Comment by kyo-ago** [comment]
Thanks for comment.
(and sorry for the late reply)

This problem has been fixed.
(ver 0.0.10)
