### ISSUE TITLE
CMS DataLife problems

### ISSUE THREAD

**Issue by LonerD** [kyo-ago/enable-right-click#3]
Extension blocks right mouse button on CMS DataLife utf-8 sites (in full news). 
As example demo-site - http://demo.dle-news.ru/o-skripte/1-post1.html
Probably, some incompatibility with CMS scripts.
Can you fix it, please?

**Comment by kyo-ago** [comment]
Thanks for comment.

But this site is very difficult...
(This is because the DOM tree has modified in the contextMenu event.)

Please exclude the domain.
(It can be set from "option" of chrome://extensions/)

// Fixed an issue where options can not be saved 😮
